# Generated by Django 3.1 on 2020-08-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre', to='bookcase_app.Genre'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='return_back_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a book genre', max_length=255),
        ),
    ]
