# Generated by Django 3.1 on 2020-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase_app', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'set_book_as_returned'),)},
        ),
    ]
